# Form implementation generated from reading ui file 'ax.tar.xz.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from time import time, ctime
import os



class Ui_OSAvoura(object):
    def setupUi(self, OSAvoura):
        OSAvoura.setObjectName("OSAvoura")
        OSAvoura.resize(801, 600)
        OSAvoura.setWindowFlags(QtCore.Qt.WindowType.CustomizeWindowHint | QtCore.Qt.WindowType.WindowCloseButtonHint | QtCore.Qt.WindowType.WindowMinimizeButtonHint)
        self.centralwidget = QtWidgets.QWidget(OSAvoura)
        self.centralwidget.setObjectName("centralwidget")
        self.taskbar = QtWidgets.QGroupBox(self.centralwidget)
        self.taskbar.setGeometry(QtCore.QRect(0, 540, 801, 61))
        self.taskbar.setTitle("")
        self.taskbar.setObjectName("taskbar")
        self.start = QtWidgets.QPushButton(self.taskbar)
        self.start.setGeometry(QtCore.QRect(10, 12, 41, 41))
        self.start.setObjectName("start")
        self.start.clicked.connect(self.startw)
        self.pushButton = QtWidgets.QPushButton(self.taskbar)
        self.pushButton.setGeometry(QtCore.QRect(60, 20, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.browser)
        self.pushButton_2 = QtWidgets.QPushButton(self.taskbar)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 20, 75, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.termi)
        self.pushButton_3 = QtWidgets.QPushButton(self.taskbar)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 20, 75, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.no)
        self.pushButton_4 = QtWidgets.QPushButton(self.taskbar)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 20, 75, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.trans)
        self.pushButton_5 = QtWidgets.QPushButton(self.taskbar)
        self.pushButton_5.setGeometry(QtCore.QRect(760, 10, 31, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.close)
        self.pushButton_6 = QtWidgets.QPushButton(self.taskbar)
        self.pushButton_6.setGeometry(QtCore.QRect(720, 10, 31, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.restart)
        self.datebar = QtWidgets.QGroupBox(self.centralwidget)
        self.datebar.setGeometry(QtCore.QRect(680, 0, 120, 41))
        self.datebar.setTitle("")
        self.datebar.setObjectName("datebar")
        self.hello = QtWidgets.QTextBrowser(self.datebar)
        self.hello.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.hello.setObjectName("hello")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 230, 118, 121))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(70, 290, 118, 121))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(210, 220, 118, 121))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(340, 260, 118, 121))
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(150, 330, 118, 121))
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(250, 120, 118, 121))
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(500, 320, 118, 121))
        self.line_7.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(60, 140, 118, 121))
        self.line_8.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(670, 340, 118, 121))
        self.line_9.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(280, 390, 118, 121))
        self.line_10.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(60, 400, 118, 121))
        self.line_11.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(460, 160, 118, 121))
        self.line_12.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(650, 130, 118, 121))
        self.line_13.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(500, 430, 118, 121))
        self.line_14.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(600, 240, 118, 121))
        self.line_15.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(360, 50, 118, 121))
        self.line_16.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_16.setObjectName("line_16")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 0, 271, 81))
        self.textBrowser_2.setObjectName("textBrowser_2")
        OSAvoura.setCentralWidget(self.centralwidget)

        self.retranslateUi(OSAvoura)
        QtCore.QMetaObject.connectSlotsByName(OSAvoura)

    def retranslateUi(self, OSAvoura):
        _translate = QtCore.QCoreApplication.translate
        OSAvoura.setWindowTitle(_translate("OSAvoura", "AvouraOS 1 on Windows 10 21H2"))
        self.start.setText(_translate("OSAvoura", "|--|"))
        self.pushButton.setText(_translate("OSAvoura", "eBrowser"))
        self.pushButton_2.setText(_translate("OSAvoura", "eTerminal"))
        self.pushButton_3.setText(_translate("OSAvoura", "eNotes"))
        self.pushButton_4.setText(_translate("OSAvoura", "eTranslator"))
        self.pushButton_5.setText(_translate("OSAvoura", "({})"))
        self.pushButton_6.setText(_translate("OSAvoura", "(_/"))
        self.t = time()
        self.time = str(ctime(self.t))
        self.hello.setText(self.time)
        self.textBrowser_2.setHtml(_translate("OSAvoura", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">OS: AvouraOS 1 Build 14235 on Windows 10 21H2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Display: 800x600 (Mini HD)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Orientation: Landscape</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ram Usage: 1.1GB (Only the app)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CPU Usage : ---</p></body></html>"))

    def browser(self):
        os.system("python xxxx.py")
        
    def startw(self):
        os.system("python start.py")
        
    def termi(self):
        os.system("python System-Drive/ter.py")
        
    def no(self):
        os.system("python notes.pyw")
        
    def trans(self):
        os.system("python t.py")
        
    def close(self):
        import sys
        sys.exit()
        
    def restart(self):
        os.system("shutdown /f /r /t 0")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OSAvoura = QtWidgets.QMainWindow()
    ui = Ui_OSAvoura()
    ui.setupUi(OSAvoura)
    OSAvoura.show()
    sys.exit(app.exec())
